House.destroy_all
Character.destroy_all

arryn = House.create({name:"House Arryn", location: "Westeros", great_house: true, motto: "As High as Honor", img_url: "http://vignette4.wikia.nocookie.net/gameofthrones/images/1/15/House-Arryn-Main-Shield.PNG/revision/latest/scale-to-width-down/250?cb=20160312101451"})
frey = House.create({name:"House Frey", location: "The Riverlands", great_house: true, motto: "We Stand Together", img_url: "http://vignette1.wikia.nocookie.net/gameofthrones/images/e/e6/House-Frey-Main-Shield.PNG/revision/latest/scale-to-width-down/250?cb=20160312124244"})
greyjoy = House.create({name:"House Greyjoy", location: "Iron Islands", great_house: true, motto: "We Do Not Sow", img_url: "http://vignette3.wikia.nocookie.net/gameofthrones/images/8/86/House-Greyjoy-Main-Shield.PNG/revision/latest/scale-to-width-down/250?cb=20160312122204"})
lannister = House.create({name:"House Lannnister", location: "The Crownlands", great_house: true, motto: "Hear Me Roar!", img_url: "http://vignette3.wikia.nocookie.net/gameofthrones/images/8/8a/House-Lannister-Main-Shield.PNG/revision/latest/scale-to-width-down/250?cb=20151207184048"})
stark = House.create({name:"House Stark", location: "The North", great_house: true, motto: "Winter is Coming", img_url: "http://vignette4.wikia.nocookie.net/gameofthrones/images/8/8a/House-Stark-Main-Shield.PNG/revision/latest/scale-to-width-down/250?cb=20160703180116"})
tully = House.create({name:"House Tully", location: "The Riverlands", great_house: false, motto: "Family, Duty, Honor", img_url: "http://vignette3.wikia.nocookie.net/gameofthrones/images/b/bd/House-Tully-Main-Shield.PNG/revision/latest/scale-to-width-down/250?cb=20160312103126"})

robin = Character.create({name:"Robin Arryn", is_dead: false, origin: "King's Landing", house: arryn, img_url: "http://vignette4.wikia.nocookie.net/gameofthrones/images/7/74/Robin_Aaryn_Book_of_Stranger.jpg/revision/latest/scale-to-width-down/270?cb=20160714005525"})
lysa = Character.create({name:"Lysa Arryn", is_dead: true, origin: "Riverrun", house: arryn, img_url: "http://vignette3.wikia.nocookie.net/gameofthrones/images/4/46/LysaArryn.png/revision/latest/scale-to-width-down/270?cb=20140523133128"})
walderrivers = Character.create({name:"Walder Rivers", is_dead: true, origin: "The Twins", house: frey, img_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/f/fb/Bastard_Walder.png/revision/latest/scale-to-width-down/270?cb=20160826005256"})
arya = Character.create({name:"Arya Stark", is_dead: false, origin: "Winterfell", house: stark, img_url: "http://vignette1.wikia.nocookie.net/gameofthrones/images/a/ad/Arya6x10.png/revision/latest/scale-to-width-down/270?cb=20160629211505"})
walderfrey = Character.create({name:"Walder Frey", is_dead: true, origin: "The Twins", house: frey, img_url: "http://vignette4.wikia.nocookie.net/gameofthrones/images/e/e4/S06E06_-_Walder_Frey_Cropped_new.jpg/revision/latest/scale-to-width-down/270?cb=20160808044705"})
balon = Character.create({name:"Balon Greyjoy", is_dead: true, origin: "Pyke", house: greyjoy, img_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/2/27/Balon_Season_6.jpg/revision/latest/scale-to-width-down/199?cb=20160211221219"})
euron = Character.create({name:"Euron Greyjoy", is_dead: false, origin: "Pyke", house: greyjoy, img_url: "http://vignette3.wikia.nocookie.net/gameofthrones/images/4/4d/Game-of-thrones-6x5_euron_promo..jpg/revision/latest/scale-to-width-down/270?cb=20160523192637"})
tyrion = Character.create({name:"Tyrion Lannister", is_dead: false, origin: "Casterly Rock", house: lannister, img_url: "http://vignette4.wikia.nocookie.net/gameofthrones/images/9/9d/Tyrion6x082.png/revision/latest/scale-to-width-down/270?cb=20160609061404"})
cersei = Character.create({name:"Cersei Lannister", is_dead: false, origin: "Casterly Rock", house: lannister, img_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/c/c7/Queen_Cersei_Main_The_winds_of_Winter.jpg/revision/latest/scale-to-width-down/270?cb=20160712032316"})
sansa = Character.create({name:"Sansa Stark", is_dead: false, origin: "Winterfell", house: stark, img_url: "http://vignette4.wikia.nocookie.net/gameofthrones/images/6/68/Sansa_stark_s6_battle_bastards_infobox.jpg/revision/latest/scale-to-width-down/270?cb=20160807084759"})
jon = Character.create({name:"Jon Snow", is_dead: false, origin: "Winterfell", house: stark, img_url: "http://vignette3.wikia.nocookie.net/gameofthrones/images/4/49/Battle_of_the_Bastards_08.jpg/revision/latest/scale-to-width-down/270?cb=20160615184845"})
edmere = Character.create({name:"Edmere Tully", is_dead: false, origin: "Riverrun", house: tully, img_url: "http://vignette2.wikia.nocookie.net/gameofthrones/images/b/b6/Edmure_Tully_Season_6.jpg/revision/latest/scale-to-width-down/270?cb=20160531175620"})
joffrey = Character.create({name:"Joffrey Baratheon", is_dead: true, origin: "King's Landing", house: lannister, img_url: "http://vignette4.wikia.nocookie.net/gameofthrones/images/e/ea/Joff_promo_shot_infobox_image.jpg/revision/latest/scale-to-width-down/270?cb=20160809044359"})
